version: '3'

services:
  db:
    image: postgres:latest
    container_name: db-application
    env_file:
      - ./rag-api-service/.env 
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - .psql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - .rd/d–∞ta:/root/redis
    
  app:
    image: llm_app
    build:
      context: ./rag-api-service
    container_name: llm_app
    env_file:
      - ./rag-api-service/.env 
    command: sh -c "alembic upgrade head && gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"    
    ports:
      - 8000:8000
    depends_on:
      - db
      
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.search.knn=true
      - ELASTIC_PASSWORD_FILE=/run/secrets/elastic_password
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    secrets:
      - elastic_password

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.search.knn=true
      - ELASTIC_PASSWORD_FILE=/run/secrets/elastic_password
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    secrets:
      - elastic_password

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.search.knn=true
      - ELASTIC_PASSWORD_FILE=/run/secrets/elastic_password
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    secrets:
      - elastic_password

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD_FILE=/run/secrets/elastic_password
    ports:
      - "5601:5601"
    depends_on:
      - es01
      - es02
      - es03
    secrets:
      - elastic_password

volumes:
  esdata01:
  esdata02:
  esdata03:

secrets:
  elastic_password:
    file: ./secrets/elastic_password.txt
