version: '3'

services:
  app:
    image: bi_encoder
    build:
      context: .
    container_name: bi_encoder
    command: sh -c "uvicorn app.main:app --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    environment:
      - HF_ENDPOINT=https://hf-mirror.com